// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ws.proto

package wsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNSPECIFIED       ControlType = 0
	ControlType_CONTROL_TYPE_SEND_MESSAGE      ControlType = 1
	ControlType_CONTROL_TYPE_SEND_REACTION     ControlType = 2
	ControlType_CONTROL_TYPE_EDIT_MESSAGE      ControlType = 3
	ControlType_CONTROL_TYPE_REVOKE_MESSAGE    ControlType = 4
	ControlType_CONTROL_TYPE_DISCONNECT        ControlType = 5
	ControlType_CONTROL_TYPE_LOGOUT            ControlType = 6
	ControlType_CONTROL_TYPE_GET_STATUS        ControlType = 7
	ControlType_CONTROL_TYPE_REQUEST_PAIR_CODE ControlType = 8
	ControlType_CONTROL_TYPE_REQUEST_PAIR_QR   ControlType = 9
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0: "CONTROL_TYPE_UNSPECIFIED",
		1: "CONTROL_TYPE_SEND_MESSAGE",
		2: "CONTROL_TYPE_SEND_REACTION",
		3: "CONTROL_TYPE_EDIT_MESSAGE",
		4: "CONTROL_TYPE_REVOKE_MESSAGE",
		5: "CONTROL_TYPE_DISCONNECT",
		6: "CONTROL_TYPE_LOGOUT",
		7: "CONTROL_TYPE_GET_STATUS",
		8: "CONTROL_TYPE_REQUEST_PAIR_CODE",
		9: "CONTROL_TYPE_REQUEST_PAIR_QR",
	}
	ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNSPECIFIED":       0,
		"CONTROL_TYPE_SEND_MESSAGE":      1,
		"CONTROL_TYPE_SEND_REACTION":     2,
		"CONTROL_TYPE_EDIT_MESSAGE":      3,
		"CONTROL_TYPE_REVOKE_MESSAGE":    4,
		"CONTROL_TYPE_DISCONNECT":        5,
		"CONTROL_TYPE_LOGOUT":            6,
		"CONTROL_TYPE_GET_STATUS":        7,
		"CONTROL_TYPE_REQUEST_PAIR_CODE": 8,
		"CONTROL_TYPE_REQUEST_PAIR_QR":   9,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_proto_enumTypes[0].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_ws_proto_enumTypes[0]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED      EventType = 0
	EventType_EVENT_TYPE_PAIR_QR          EventType = 1
	EventType_EVENT_TYPE_PAIR_CODE        EventType = 2
	EventType_EVENT_TYPE_PAIR_SUCCESS     EventType = 3
	EventType_EVENT_TYPE_PAIR_ERROR       EventType = 4
	EventType_EVENT_TYPE_LOGGED_OUT       EventType = 5
	EventType_EVENT_TYPE_DISCONNECTED     EventType = 6
	EventType_EVENT_TYPE_CONNECTED        EventType = 7
	EventType_EVENT_TYPE_INCOMING_MESSAGE EventType = 8
	EventType_EVENT_TYPE_INCOMING_CALL    EventType = 9
	EventType_EVENT_TYPE_ACK              EventType = 10
	EventType_EVENT_TYPE_STATUS           EventType = 11
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PAIR_QR",
		2:  "EVENT_TYPE_PAIR_CODE",
		3:  "EVENT_TYPE_PAIR_SUCCESS",
		4:  "EVENT_TYPE_PAIR_ERROR",
		5:  "EVENT_TYPE_LOGGED_OUT",
		6:  "EVENT_TYPE_DISCONNECTED",
		7:  "EVENT_TYPE_CONNECTED",
		8:  "EVENT_TYPE_INCOMING_MESSAGE",
		9:  "EVENT_TYPE_INCOMING_CALL",
		10: "EVENT_TYPE_ACK",
		11: "EVENT_TYPE_STATUS",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":      0,
		"EVENT_TYPE_PAIR_QR":          1,
		"EVENT_TYPE_PAIR_CODE":        2,
		"EVENT_TYPE_PAIR_SUCCESS":     3,
		"EVENT_TYPE_PAIR_ERROR":       4,
		"EVENT_TYPE_LOGGED_OUT":       5,
		"EVENT_TYPE_DISCONNECTED":     6,
		"EVENT_TYPE_CONNECTED":        7,
		"EVENT_TYPE_INCOMING_MESSAGE": 8,
		"EVENT_TYPE_INCOMING_CALL":    9,
		"EVENT_TYPE_ACK":              10,
		"EVENT_TYPE_STATUS":           11,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_ws_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

// ControlFrame is sent by WebSocket clients to control the bot daemon.
type ControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ControlType            `protobuf:"varint,1,opt,name=type,proto3,enum=whatsrook.ws.ControlType" json:"type,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlFrame_SendMessage
	//	*ControlFrame_SendReaction
	//	*ControlFrame_EditMessage
	//	*ControlFrame_RevokeMessage
	//	*ControlFrame_GetStatus
	//	*ControlFrame_Disconnect
	//	*ControlFrame_Logout
	//	*ControlFrame_RequestPairCode
	//	*ControlFrame_RequestPairQr
	Payload       isControlFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *ControlFrame) GetType() ControlType {
	if x != nil {
		return x.Type
	}
	return ControlType_CONTROL_TYPE_UNSPECIFIED
}

func (x *ControlFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlFrame) GetPayload() isControlFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlFrame) GetSendMessage() *SendMessagePayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ControlFrame) GetSendReaction() *SendReactionPayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_SendReaction); ok {
			return x.SendReaction
		}
	}
	return nil
}

func (x *ControlFrame) GetEditMessage() *EditMessagePayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_EditMessage); ok {
			return x.EditMessage
		}
	}
	return nil
}

func (x *ControlFrame) GetRevokeMessage() *RevokeMessagePayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_RevokeMessage); ok {
			return x.RevokeMessage
		}
	}
	return nil
}

func (x *ControlFrame) GetGetStatus() *GetStatusPayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_GetStatus); ok {
			return x.GetStatus
		}
	}
	return nil
}

func (x *ControlFrame) GetDisconnect() *DisconnectPayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *ControlFrame) GetLogout() *LogoutPayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

func (x *ControlFrame) GetRequestPairCode() *RequestPairCodePayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_RequestPairCode); ok {
			return x.RequestPairCode
		}
	}
	return nil
}

func (x *ControlFrame) GetRequestPairQr() *RequestPairQRPayload {
	if x != nil {
		if x, ok := x.Payload.(*ControlFrame_RequestPairQr); ok {
			return x.RequestPairQr
		}
	}
	return nil
}

type isControlFrame_Payload interface {
	isControlFrame_Payload()
}

type ControlFrame_SendMessage struct {
	SendMessage *SendMessagePayload `protobuf:"bytes,3,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ControlFrame_SendReaction struct {
	SendReaction *SendReactionPayload `protobuf:"bytes,4,opt,name=send_reaction,json=sendReaction,proto3,oneof"`
}

type ControlFrame_EditMessage struct {
	EditMessage *EditMessagePayload `protobuf:"bytes,5,opt,name=edit_message,json=editMessage,proto3,oneof"`
}

type ControlFrame_RevokeMessage struct {
	RevokeMessage *RevokeMessagePayload `protobuf:"bytes,6,opt,name=revoke_message,json=revokeMessage,proto3,oneof"`
}

type ControlFrame_GetStatus struct {
	GetStatus *GetStatusPayload `protobuf:"bytes,7,opt,name=get_status,json=getStatus,proto3,oneof"`
}

type ControlFrame_Disconnect struct {
	Disconnect *DisconnectPayload `protobuf:"bytes,8,opt,name=disconnect,proto3,oneof"`
}

type ControlFrame_Logout struct {
	Logout *LogoutPayload `protobuf:"bytes,9,opt,name=logout,proto3,oneof"`
}

type ControlFrame_RequestPairCode struct {
	RequestPairCode *RequestPairCodePayload `protobuf:"bytes,10,opt,name=request_pair_code,json=requestPairCode,proto3,oneof"`
}

type ControlFrame_RequestPairQr struct {
	RequestPairQr *RequestPairQRPayload `protobuf:"bytes,11,opt,name=request_pair_qr,json=requestPairQr,proto3,oneof"`
}

func (*ControlFrame_SendMessage) isControlFrame_Payload() {}

func (*ControlFrame_SendReaction) isControlFrame_Payload() {}

func (*ControlFrame_EditMessage) isControlFrame_Payload() {}

func (*ControlFrame_RevokeMessage) isControlFrame_Payload() {}

func (*ControlFrame_GetStatus) isControlFrame_Payload() {}

func (*ControlFrame_Disconnect) isControlFrame_Payload() {}

func (*ControlFrame_Logout) isControlFrame_Payload() {}

func (*ControlFrame_RequestPairCode) isControlFrame_Payload() {}

func (*ControlFrame_RequestPairQr) isControlFrame_Payload() {}

type RequestPairCodePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairCodePayload) Reset() {
	*x = RequestPairCodePayload{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairCodePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairCodePayload) ProtoMessage() {}

func (x *RequestPairCodePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairCodePayload.ProtoReflect.Descriptor instead.
func (*RequestPairCodePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

func (x *RequestPairCodePayload) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type RequestPairQRPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairQRPayload) Reset() {
	*x = RequestPairQRPayload{}
	mi := &file_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairQRPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairQRPayload) ProtoMessage() {}

func (x *RequestPairQRPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairQRPayload.ProtoReflect.Descriptor instead.
func (*RequestPairQRPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2}
}

// EventFrame is sent by the bot daemon to connected WebSocket clients.
type EventFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=whatsrook.ws.EventType" json:"type,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventFrame_Ack
	//	*EventFrame_Status
	//	*EventFrame_PairQr
	//	*EventFrame_PairCode
	//	*EventFrame_PairError
	//	*EventFrame_Message
	//	*EventFrame_IncomingCall
	Payload       isEventFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{3}
}

func (x *EventFrame) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventFrame) GetPayload() isEventFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventFrame) GetAck() *AckPayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *EventFrame) GetStatus() *StatusPayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *EventFrame) GetPairQr() *PairQRPayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_PairQr); ok {
			return x.PairQr
		}
	}
	return nil
}

func (x *EventFrame) GetPairCode() *PairCodePayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_PairCode); ok {
			return x.PairCode
		}
	}
	return nil
}

func (x *EventFrame) GetPairError() *PairErrorPayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_PairError); ok {
			return x.PairError
		}
	}
	return nil
}

func (x *EventFrame) GetMessage() *IncomingMessagePayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *EventFrame) GetIncomingCall() *IncomingCallPayload {
	if x != nil {
		if x, ok := x.Payload.(*EventFrame_IncomingCall); ok {
			return x.IncomingCall
		}
	}
	return nil
}

type isEventFrame_Payload interface {
	isEventFrame_Payload()
}

type EventFrame_Ack struct {
	Ack *AckPayload `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type EventFrame_Status struct {
	Status *StatusPayload `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type EventFrame_PairQr struct {
	PairQr *PairQRPayload `protobuf:"bytes,5,opt,name=pair_qr,json=pairQr,proto3,oneof"`
}

type EventFrame_PairCode struct {
	PairCode *PairCodePayload `protobuf:"bytes,6,opt,name=pair_code,json=pairCode,proto3,oneof"`
}

type EventFrame_PairError struct {
	PairError *PairErrorPayload `protobuf:"bytes,7,opt,name=pair_error,json=pairError,proto3,oneof"`
}

type EventFrame_Message struct {
	Message *IncomingMessagePayload `protobuf:"bytes,8,opt,name=message,proto3,oneof"`
}

type EventFrame_IncomingCall struct {
	IncomingCall *IncomingCallPayload `protobuf:"bytes,9,opt,name=incoming_call,json=incomingCall,proto3,oneof"`
}

func (*EventFrame_Ack) isEventFrame_Payload() {}

func (*EventFrame_Status) isEventFrame_Payload() {}

func (*EventFrame_PairQr) isEventFrame_Payload() {}

func (*EventFrame_PairCode) isEventFrame_Payload() {}

func (*EventFrame_PairError) isEventFrame_Payload() {}

func (*EventFrame_Message) isEventFrame_Payload() {}

func (*EventFrame_IncomingCall) isEventFrame_Payload() {}

type SendMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	QuoteId       *string                `protobuf:"bytes,3,opt,name=quote_id,json=quoteId,proto3,oneof" json:"quote_id,omitempty"`
	QuoteSender   *string                `protobuf:"bytes,4,opt,name=quote_sender,json=quoteSender,proto3,oneof" json:"quote_sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessagePayload) Reset() {
	*x = SendMessagePayload{}
	mi := &file_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessagePayload) ProtoMessage() {}

func (x *SendMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessagePayload.ProtoReflect.Descriptor instead.
func (*SendMessagePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessagePayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMessagePayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessagePayload) GetQuoteId() string {
	if x != nil && x.QuoteId != nil {
		return *x.QuoteId
	}
	return ""
}

func (x *SendMessagePayload) GetQuoteSender() string {
	if x != nil && x.QuoteSender != nil {
		return *x.QuoteSender
	}
	return ""
}

type SendReactionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Sender        *string                `protobuf:"bytes,3,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Emoji         string                 `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReactionPayload) Reset() {
	*x = SendReactionPayload{}
	mi := &file_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReactionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReactionPayload) ProtoMessage() {}

func (x *SendReactionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReactionPayload.ProtoReflect.Descriptor instead.
func (*SendReactionPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{5}
}

func (x *SendReactionPayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendReactionPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendReactionPayload) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *SendReactionPayload) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type EditMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NewText       string                 `protobuf:"bytes,3,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessagePayload) Reset() {
	*x = EditMessagePayload{}
	mi := &file_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessagePayload) ProtoMessage() {}

func (x *EditMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessagePayload.ProtoReflect.Descriptor instead.
func (*EditMessagePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{6}
}

func (x *EditMessagePayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EditMessagePayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessagePayload) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type RevokeMessagePayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	To             string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	OriginalSender *string                `protobuf:"bytes,3,opt,name=original_sender,json=originalSender,proto3,oneof" json:"original_sender,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeMessagePayload) Reset() {
	*x = RevokeMessagePayload{}
	mi := &file_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessagePayload) ProtoMessage() {}

func (x *RevokeMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessagePayload.ProtoReflect.Descriptor instead.
func (*RevokeMessagePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeMessagePayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RevokeMessagePayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RevokeMessagePayload) GetOriginalSender() string {
	if x != nil && x.OriginalSender != nil {
		return *x.OriginalSender
	}
	return ""
}

type GetStatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusPayload) Reset() {
	*x = GetStatusPayload{}
	mi := &file_ws_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusPayload) ProtoMessage() {}

func (x *GetStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusPayload.ProtoReflect.Descriptor instead.
func (*GetStatusPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{8}
}

type DisconnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectPayload) Reset() {
	*x = DisconnectPayload{}
	mi := &file_ws_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectPayload) ProtoMessage() {}

func (x *DisconnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectPayload.ProtoReflect.Descriptor instead.
func (*DisconnectPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{9}
}

type LogoutPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutPayload) Reset() {
	*x = LogoutPayload{}
	mi := &file_ws_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutPayload) ProtoMessage() {}

func (x *LogoutPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutPayload.ProtoReflect.Descriptor instead.
func (*LogoutPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{10}
}

type AckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPayload) Reset() {
	*x = AckPayload{}
	mi := &file_ws_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPayload) ProtoMessage() {}

func (x *AckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPayload.ProtoReflect.Descriptor instead.
func (*AckPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{11}
}

func (x *AckPayload) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AckPayload) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type StatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	LoggedIn      bool                   `protobuf:"varint,2,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	Jid           *string                `protobuf:"bytes,3,opt,name=jid,proto3,oneof" json:"jid,omitempty"`
	PushName      *string                `protobuf:"bytes,4,opt,name=push_name,json=pushName,proto3,oneof" json:"push_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusPayload) Reset() {
	*x = StatusPayload{}
	mi := &file_ws_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusPayload) ProtoMessage() {}

func (x *StatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusPayload.ProtoReflect.Descriptor instead.
func (*StatusPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{12}
}

func (x *StatusPayload) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *StatusPayload) GetLoggedIn() bool {
	if x != nil {
		return x.LoggedIn
	}
	return false
}

func (x *StatusPayload) GetJid() string {
	if x != nil && x.Jid != nil {
		return *x.Jid
	}
	return ""
}

func (x *StatusPayload) GetPushName() string {
	if x != nil && x.PushName != nil {
		return *x.PushName
	}
	return ""
}

type PairQRPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairQRPayload) Reset() {
	*x = PairQRPayload{}
	mi := &file_ws_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairQRPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairQRPayload) ProtoMessage() {}

func (x *PairQRPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairQRPayload.ProtoReflect.Descriptor instead.
func (*PairQRPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{13}
}

func (x *PairQRPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PairCodePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairCodePayload) Reset() {
	*x = PairCodePayload{}
	mi := &file_ws_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairCodePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairCodePayload) ProtoMessage() {}

func (x *PairCodePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairCodePayload.ProtoReflect.Descriptor instead.
func (*PairCodePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{14}
}

func (x *PairCodePayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PairErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairErrorPayload) Reset() {
	*x = PairErrorPayload{}
	mi := &file_ws_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairErrorPayload) ProtoMessage() {}

func (x *PairErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairErrorPayload.ProtoReflect.Descriptor instead.
func (*PairErrorPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{15}
}

func (x *PairErrorPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IncomingMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Chat          string                 `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	MessageId     string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PushName      *string                `protobuf:"bytes,6,opt,name=push_name,json=pushName,proto3,oneof" json:"push_name,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	IsGroup       bool                   `protobuf:"varint,8,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	IsFromMe      bool                   `protobuf:"varint,9,opt,name=is_from_me,json=isFromMe,proto3" json:"is_from_me,omitempty"`
	MediaType     *string                `protobuf:"bytes,10,opt,name=media_type,json=mediaType,proto3,oneof" json:"media_type,omitempty"`
	QuotedId      *string                `protobuf:"bytes,11,opt,name=quoted_id,json=quotedId,proto3,oneof" json:"quoted_id,omitempty"`
	QuotedText    *string                `protobuf:"bytes,12,opt,name=quoted_text,json=quotedText,proto3,oneof" json:"quoted_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessagePayload) Reset() {
	*x = IncomingMessagePayload{}
	mi := &file_ws_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessagePayload) ProtoMessage() {}

func (x *IncomingMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessagePayload.ProtoReflect.Descriptor instead.
func (*IncomingMessagePayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{16}
}

func (x *IncomingMessagePayload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IncomingMessagePayload) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *IncomingMessagePayload) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *IncomingMessagePayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IncomingMessagePayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *IncomingMessagePayload) GetPushName() string {
	if x != nil && x.PushName != nil {
		return *x.PushName
	}
	return ""
}

func (x *IncomingMessagePayload) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *IncomingMessagePayload) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *IncomingMessagePayload) GetIsFromMe() bool {
	if x != nil {
		return x.IsFromMe
	}
	return false
}

func (x *IncomingMessagePayload) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *IncomingMessagePayload) GetQuotedId() string {
	if x != nil && x.QuotedId != nil {
		return *x.QuotedId
	}
	return ""
}

func (x *IncomingMessagePayload) GetQuotedText() string {
	if x != nil && x.QuotedText != nil {
		return *x.QuotedText
	}
	return ""
}

type IncomingCallPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallPayload) Reset() {
	*x = IncomingCallPayload{}
	mi := &file_ws_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallPayload) ProtoMessage() {}

func (x *IncomingCallPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallPayload.ProtoReflect.Descriptor instead.
func (*IncomingCallPayload) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{17}
}

func (x *IncomingCallPayload) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IncomingCallPayload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IncomingCallPayload) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\x12\fwhatsrook.ws\"\xda\x05\n" +
	"\fControlFrame\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.whatsrook.ws.ControlTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12E\n" +
	"\fsend_message\x18\x03 \x01(\v2 .whatsrook.ws.SendMessagePayloadH\x00R\vsendMessage\x12H\n" +
	"\rsend_reaction\x18\x04 \x01(\v2!.whatsrook.ws.SendReactionPayloadH\x00R\fsendReaction\x12E\n" +
	"\fedit_message\x18\x05 \x01(\v2 .whatsrook.ws.EditMessagePayloadH\x00R\veditMessage\x12K\n" +
	"\x0erevoke_message\x18\x06 \x01(\v2\".whatsrook.ws.RevokeMessagePayloadH\x00R\rrevokeMessage\x12?\n" +
	"\n" +
	"get_status\x18\a \x01(\v2\x1e.whatsrook.ws.GetStatusPayloadH\x00R\tgetStatus\x12A\n" +
	"\n" +
	"disconnect\x18\b \x01(\v2\x1f.whatsrook.ws.DisconnectPayloadH\x00R\n" +
	"disconnect\x125\n" +
	"\x06logout\x18\t \x01(\v2\x1b.whatsrook.ws.LogoutPayloadH\x00R\x06logout\x12R\n" +
	"\x11request_pair_code\x18\n" +
	" \x01(\v2$.whatsrook.ws.RequestPairCodePayloadH\x00R\x0frequestPairCode\x12L\n" +
	"\x0frequest_pair_qr\x18\v \x01(\v2\".whatsrook.ws.RequestPairQRPayloadH\x00R\rrequestPairQrB\t\n" +
	"\apayload\";\n" +
	"\x16RequestPairCodePayload\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"\x16\n" +
	"\x14RequestPairQRPayload\"\xfc\x03\n" +
	"\n" +
	"EventFrame\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.whatsrook.ws.EventTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.whatsrook.ws.AckPayloadH\x00R\x03ack\x125\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.whatsrook.ws.StatusPayloadH\x00R\x06status\x126\n" +
	"\apair_qr\x18\x05 \x01(\v2\x1b.whatsrook.ws.PairQRPayloadH\x00R\x06pairQr\x12<\n" +
	"\tpair_code\x18\x06 \x01(\v2\x1d.whatsrook.ws.PairCodePayloadH\x00R\bpairCode\x12?\n" +
	"\n" +
	"pair_error\x18\a \x01(\v2\x1e.whatsrook.ws.PairErrorPayloadH\x00R\tpairError\x12@\n" +
	"\amessage\x18\b \x01(\v2$.whatsrook.ws.IncomingMessagePayloadH\x00R\amessage\x12H\n" +
	"\rincoming_call\x18\t \x01(\v2!.whatsrook.ws.IncomingCallPayloadH\x00R\fincomingCallB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\x12SendMessagePayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\bquote_id\x18\x03 \x01(\tH\x00R\aquoteId\x88\x01\x01\x12&\n" +
	"\fquote_sender\x18\x04 \x01(\tH\x01R\vquoteSender\x88\x01\x01B\v\n" +
	"\t_quote_idB\x0f\n" +
	"\r_quote_sender\"\x82\x01\n" +
	"\x13SendReactionPayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\x06sender\x18\x03 \x01(\tH\x00R\x06sender\x88\x01\x01\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emojiB\t\n" +
	"\a_sender\"^\n" +
	"\x12EditMessagePayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x19\n" +
	"\bnew_text\x18\x03 \x01(\tR\anewText\"\x87\x01\n" +
	"\x14RevokeMessagePayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12,\n" +
	"\x0foriginal_sender\x18\x03 \x01(\tH\x00R\x0eoriginalSender\x88\x01\x01B\x12\n" +
	"\x10_original_sender\"\x12\n" +
	"\x10GetStatusPayload\"\x13\n" +
	"\x11DisconnectPayload\"\x0f\n" +
	"\rLogoutPayload\"A\n" +
	"\n" +
	"AckPayload\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x99\x01\n" +
	"\rStatusPayload\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1b\n" +
	"\tlogged_in\x18\x02 \x01(\bR\bloggedIn\x12\x15\n" +
	"\x03jid\x18\x03 \x01(\tH\x00R\x03jid\x88\x01\x01\x12 \n" +
	"\tpush_name\x18\x04 \x01(\tH\x01R\bpushName\x88\x01\x01B\x06\n" +
	"\x04_jidB\f\n" +
	"\n" +
	"_push_name\"#\n" +
	"\rPairQRPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"%\n" +
	"\x0fPairCodePayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"*\n" +
	"\x10PairErrorPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xb4\x03\n" +
	"\x16IncomingMessagePayload\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x12\n" +
	"\x04chat\x18\x02 \x01(\tR\x04chat\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\x12 \n" +
	"\tpush_name\x18\x06 \x01(\tH\x00R\bpushName\x88\x01\x01\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\x12\x19\n" +
	"\bis_group\x18\b \x01(\bR\aisGroup\x12\x1c\n" +
	"\n" +
	"is_from_me\x18\t \x01(\bR\bisFromMe\x12\"\n" +
	"\n" +
	"media_type\x18\n" +
	" \x01(\tH\x01R\tmediaType\x88\x01\x01\x12 \n" +
	"\tquoted_id\x18\v \x01(\tH\x02R\bquotedId\x88\x01\x01\x12$\n" +
	"\vquoted_text\x18\f \x01(\tH\x03R\n" +
	"quotedText\x88\x01\x01B\f\n" +
	"\n" +
	"_push_nameB\r\n" +
	"\v_media_typeB\f\n" +
	"\n" +
	"_quoted_idB\x0e\n" +
	"\f_quoted_text\"i\n" +
	"\x13IncomingCallPayload\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix*\xc3\x02\n" +
	"\vControlType\x12\x1c\n" +
	"\x18CONTROL_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONTROL_TYPE_SEND_MESSAGE\x10\x01\x12\x1e\n" +
	"\x1aCONTROL_TYPE_SEND_REACTION\x10\x02\x12\x1d\n" +
	"\x19CONTROL_TYPE_EDIT_MESSAGE\x10\x03\x12\x1f\n" +
	"\x1bCONTROL_TYPE_REVOKE_MESSAGE\x10\x04\x12\x1b\n" +
	"\x17CONTROL_TYPE_DISCONNECT\x10\x05\x12\x17\n" +
	"\x13CONTROL_TYPE_LOGOUT\x10\x06\x12\x1b\n" +
	"\x17CONTROL_TYPE_GET_STATUS\x10\a\x12\"\n" +
	"\x1eCONTROL_TYPE_REQUEST_PAIR_CODE\x10\b\x12 \n" +
	"\x1cCONTROL_TYPE_REQUEST_PAIR_QR\x10\t*\xcd\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_PAIR_QR\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_PAIR_CODE\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_PAIR_SUCCESS\x10\x03\x12\x19\n" +
	"\x15EVENT_TYPE_PAIR_ERROR\x10\x04\x12\x19\n" +
	"\x15EVENT_TYPE_LOGGED_OUT\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_DISCONNECTED\x10\x06\x12\x18\n" +
	"\x14EVENT_TYPE_CONNECTED\x10\a\x12\x1f\n" +
	"\x1bEVENT_TYPE_INCOMING_MESSAGE\x10\b\x12\x1c\n" +
	"\x18EVENT_TYPE_INCOMING_CALL\x10\t\x12\x12\n" +
	"\x0eEVENT_TYPE_ACK\x10\n" +
	"\x12\x15\n" +
	"\x11EVENT_TYPE_STATUS\x10\vB+Z)github.com/Thruqe/whatsrook/proto/wsprotob\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ws_proto_goTypes = []any{
	(ControlType)(0),               // 0: whatsrook.ws.ControlType
	(EventType)(0),                 // 1: whatsrook.ws.EventType
	(*ControlFrame)(nil),           // 2: whatsrook.ws.ControlFrame
	(*RequestPairCodePayload)(nil), // 3: whatsrook.ws.RequestPairCodePayload
	(*RequestPairQRPayload)(nil),   // 4: whatsrook.ws.RequestPairQRPayload
	(*EventFrame)(nil),             // 5: whatsrook.ws.EventFrame
	(*SendMessagePayload)(nil),     // 6: whatsrook.ws.SendMessagePayload
	(*SendReactionPayload)(nil),    // 7: whatsrook.ws.SendReactionPayload
	(*EditMessagePayload)(nil),     // 8: whatsrook.ws.EditMessagePayload
	(*RevokeMessagePayload)(nil),   // 9: whatsrook.ws.RevokeMessagePayload
	(*GetStatusPayload)(nil),       // 10: whatsrook.ws.GetStatusPayload
	(*DisconnectPayload)(nil),      // 11: whatsrook.ws.DisconnectPayload
	(*LogoutPayload)(nil),          // 12: whatsrook.ws.LogoutPayload
	(*AckPayload)(nil),             // 13: whatsrook.ws.AckPayload
	(*StatusPayload)(nil),          // 14: whatsrook.ws.StatusPayload
	(*PairQRPayload)(nil),          // 15: whatsrook.ws.PairQRPayload
	(*PairCodePayload)(nil),        // 16: whatsrook.ws.PairCodePayload
	(*PairErrorPayload)(nil),       // 17: whatsrook.ws.PairErrorPayload
	(*IncomingMessagePayload)(nil), // 18: whatsrook.ws.IncomingMessagePayload
	(*IncomingCallPayload)(nil),    // 19: whatsrook.ws.IncomingCallPayload
}
var file_ws_proto_depIdxs = []int32{
	0,  // 0: whatsrook.ws.ControlFrame.type:type_name -> whatsrook.ws.ControlType
	6,  // 1: whatsrook.ws.ControlFrame.send_message:type_name -> whatsrook.ws.SendMessagePayload
	7,  // 2: whatsrook.ws.ControlFrame.send_reaction:type_name -> whatsrook.ws.SendReactionPayload
	8,  // 3: whatsrook.ws.ControlFrame.edit_message:type_name -> whatsrook.ws.EditMessagePayload
	9,  // 4: whatsrook.ws.ControlFrame.revoke_message:type_name -> whatsrook.ws.RevokeMessagePayload
	10, // 5: whatsrook.ws.ControlFrame.get_status:type_name -> whatsrook.ws.GetStatusPayload
	11, // 6: whatsrook.ws.ControlFrame.disconnect:type_name -> whatsrook.ws.DisconnectPayload
	12, // 7: whatsrook.ws.ControlFrame.logout:type_name -> whatsrook.ws.LogoutPayload
	3,  // 8: whatsrook.ws.ControlFrame.request_pair_code:type_name -> whatsrook.ws.RequestPairCodePayload
	4,  // 9: whatsrook.ws.ControlFrame.request_pair_qr:type_name -> whatsrook.ws.RequestPairQRPayload
	1,  // 10: whatsrook.ws.EventFrame.type:type_name -> whatsrook.ws.EventType
	13, // 11: whatsrook.ws.EventFrame.ack:type_name -> whatsrook.ws.AckPayload
	14, // 12: whatsrook.ws.EventFrame.status:type_name -> whatsrook.ws.StatusPayload
	15, // 13: whatsrook.ws.EventFrame.pair_qr:type_name -> whatsrook.ws.PairQRPayload
	16, // 14: whatsrook.ws.EventFrame.pair_code:type_name -> whatsrook.ws.PairCodePayload
	17, // 15: whatsrook.ws.EventFrame.pair_error:type_name -> whatsrook.ws.PairErrorPayload
	18, // 16: whatsrook.ws.EventFrame.message:type_name -> whatsrook.ws.IncomingMessagePayload
	19, // 17: whatsrook.ws.EventFrame.incoming_call:type_name -> whatsrook.ws.IncomingCallPayload
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	file_ws_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlFrame_SendMessage)(nil),
		(*ControlFrame_SendReaction)(nil),
		(*ControlFrame_EditMessage)(nil),
		(*ControlFrame_RevokeMessage)(nil),
		(*ControlFrame_GetStatus)(nil),
		(*ControlFrame_Disconnect)(nil),
		(*ControlFrame_Logout)(nil),
		(*ControlFrame_RequestPairCode)(nil),
		(*ControlFrame_RequestPairQr)(nil),
	}
	file_ws_proto_msgTypes[3].OneofWrappers = []any{
		(*EventFrame_Ack)(nil),
		(*EventFrame_Status)(nil),
		(*EventFrame_PairQr)(nil),
		(*EventFrame_PairCode)(nil),
		(*EventFrame_PairError)(nil),
		(*EventFrame_Message)(nil),
		(*EventFrame_IncomingCall)(nil),
	}
	file_ws_proto_msgTypes[4].OneofWrappers = []any{}
	file_ws_proto_msgTypes[5].OneofWrappers = []any{}
	file_ws_proto_msgTypes[7].OneofWrappers = []any{}
	file_ws_proto_msgTypes[11].OneofWrappers = []any{}
	file_ws_proto_msgTypes[12].OneofWrappers = []any{}
	file_ws_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		EnumInfos:         file_ws_proto_enumTypes,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
