// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.19.6
// source: ws.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "whatsrook.ws";

export enum ControlType {
  CONTROL_TYPE_UNSPECIFIED = 0,
  CONTROL_TYPE_SEND_MESSAGE = 1,
  CONTROL_TYPE_SEND_REACTION = 2,
  CONTROL_TYPE_EDIT_MESSAGE = 3,
  CONTROL_TYPE_REVOKE_MESSAGE = 4,
  CONTROL_TYPE_DISCONNECT = 5,
  CONTROL_TYPE_LOGOUT = 6,
  CONTROL_TYPE_GET_STATUS = 7,
  CONTROL_TYPE_REQUEST_PAIR_CODE = 8,
  CONTROL_TYPE_REQUEST_PAIR_QR = 9,
  UNRECOGNIZED = -1,
}

export function controlTypeFromJSON(object: any): ControlType {
  switch (object) {
    case 0:
    case "CONTROL_TYPE_UNSPECIFIED":
      return ControlType.CONTROL_TYPE_UNSPECIFIED;
    case 1:
    case "CONTROL_TYPE_SEND_MESSAGE":
      return ControlType.CONTROL_TYPE_SEND_MESSAGE;
    case 2:
    case "CONTROL_TYPE_SEND_REACTION":
      return ControlType.CONTROL_TYPE_SEND_REACTION;
    case 3:
    case "CONTROL_TYPE_EDIT_MESSAGE":
      return ControlType.CONTROL_TYPE_EDIT_MESSAGE;
    case 4:
    case "CONTROL_TYPE_REVOKE_MESSAGE":
      return ControlType.CONTROL_TYPE_REVOKE_MESSAGE;
    case 5:
    case "CONTROL_TYPE_DISCONNECT":
      return ControlType.CONTROL_TYPE_DISCONNECT;
    case 6:
    case "CONTROL_TYPE_LOGOUT":
      return ControlType.CONTROL_TYPE_LOGOUT;
    case 7:
    case "CONTROL_TYPE_GET_STATUS":
      return ControlType.CONTROL_TYPE_GET_STATUS;
    case 8:
    case "CONTROL_TYPE_REQUEST_PAIR_CODE":
      return ControlType.CONTROL_TYPE_REQUEST_PAIR_CODE;
    case 9:
    case "CONTROL_TYPE_REQUEST_PAIR_QR":
      return ControlType.CONTROL_TYPE_REQUEST_PAIR_QR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ControlType.UNRECOGNIZED;
  }
}

export function controlTypeToJSON(object: ControlType): string {
  switch (object) {
    case ControlType.CONTROL_TYPE_UNSPECIFIED:
      return "CONTROL_TYPE_UNSPECIFIED";
    case ControlType.CONTROL_TYPE_SEND_MESSAGE:
      return "CONTROL_TYPE_SEND_MESSAGE";
    case ControlType.CONTROL_TYPE_SEND_REACTION:
      return "CONTROL_TYPE_SEND_REACTION";
    case ControlType.CONTROL_TYPE_EDIT_MESSAGE:
      return "CONTROL_TYPE_EDIT_MESSAGE";
    case ControlType.CONTROL_TYPE_REVOKE_MESSAGE:
      return "CONTROL_TYPE_REVOKE_MESSAGE";
    case ControlType.CONTROL_TYPE_DISCONNECT:
      return "CONTROL_TYPE_DISCONNECT";
    case ControlType.CONTROL_TYPE_LOGOUT:
      return "CONTROL_TYPE_LOGOUT";
    case ControlType.CONTROL_TYPE_GET_STATUS:
      return "CONTROL_TYPE_GET_STATUS";
    case ControlType.CONTROL_TYPE_REQUEST_PAIR_CODE:
      return "CONTROL_TYPE_REQUEST_PAIR_CODE";
    case ControlType.CONTROL_TYPE_REQUEST_PAIR_QR:
      return "CONTROL_TYPE_REQUEST_PAIR_QR";
    case ControlType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0,
  EVENT_TYPE_PAIR_QR = 1,
  EVENT_TYPE_PAIR_CODE = 2,
  EVENT_TYPE_PAIR_SUCCESS = 3,
  EVENT_TYPE_PAIR_ERROR = 4,
  EVENT_TYPE_LOGGED_OUT = 5,
  EVENT_TYPE_DISCONNECTED = 6,
  EVENT_TYPE_CONNECTED = 7,
  EVENT_TYPE_INCOMING_MESSAGE = 8,
  EVENT_TYPE_INCOMING_CALL = 9,
  EVENT_TYPE_ACK = 10,
  EVENT_TYPE_STATUS = 11,
  UNRECOGNIZED = -1,
}

export function eventTypeFromJSON(object: any): EventType {
  switch (object) {
    case 0:
    case "EVENT_TYPE_UNSPECIFIED":
      return EventType.EVENT_TYPE_UNSPECIFIED;
    case 1:
    case "EVENT_TYPE_PAIR_QR":
      return EventType.EVENT_TYPE_PAIR_QR;
    case 2:
    case "EVENT_TYPE_PAIR_CODE":
      return EventType.EVENT_TYPE_PAIR_CODE;
    case 3:
    case "EVENT_TYPE_PAIR_SUCCESS":
      return EventType.EVENT_TYPE_PAIR_SUCCESS;
    case 4:
    case "EVENT_TYPE_PAIR_ERROR":
      return EventType.EVENT_TYPE_PAIR_ERROR;
    case 5:
    case "EVENT_TYPE_LOGGED_OUT":
      return EventType.EVENT_TYPE_LOGGED_OUT;
    case 6:
    case "EVENT_TYPE_DISCONNECTED":
      return EventType.EVENT_TYPE_DISCONNECTED;
    case 7:
    case "EVENT_TYPE_CONNECTED":
      return EventType.EVENT_TYPE_CONNECTED;
    case 8:
    case "EVENT_TYPE_INCOMING_MESSAGE":
      return EventType.EVENT_TYPE_INCOMING_MESSAGE;
    case 9:
    case "EVENT_TYPE_INCOMING_CALL":
      return EventType.EVENT_TYPE_INCOMING_CALL;
    case 10:
    case "EVENT_TYPE_ACK":
      return EventType.EVENT_TYPE_ACK;
    case 11:
    case "EVENT_TYPE_STATUS":
      return EventType.EVENT_TYPE_STATUS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EventType.UNRECOGNIZED;
  }
}

export function eventTypeToJSON(object: EventType): string {
  switch (object) {
    case EventType.EVENT_TYPE_UNSPECIFIED:
      return "EVENT_TYPE_UNSPECIFIED";
    case EventType.EVENT_TYPE_PAIR_QR:
      return "EVENT_TYPE_PAIR_QR";
    case EventType.EVENT_TYPE_PAIR_CODE:
      return "EVENT_TYPE_PAIR_CODE";
    case EventType.EVENT_TYPE_PAIR_SUCCESS:
      return "EVENT_TYPE_PAIR_SUCCESS";
    case EventType.EVENT_TYPE_PAIR_ERROR:
      return "EVENT_TYPE_PAIR_ERROR";
    case EventType.EVENT_TYPE_LOGGED_OUT:
      return "EVENT_TYPE_LOGGED_OUT";
    case EventType.EVENT_TYPE_DISCONNECTED:
      return "EVENT_TYPE_DISCONNECTED";
    case EventType.EVENT_TYPE_CONNECTED:
      return "EVENT_TYPE_CONNECTED";
    case EventType.EVENT_TYPE_INCOMING_MESSAGE:
      return "EVENT_TYPE_INCOMING_MESSAGE";
    case EventType.EVENT_TYPE_INCOMING_CALL:
      return "EVENT_TYPE_INCOMING_CALL";
    case EventType.EVENT_TYPE_ACK:
      return "EVENT_TYPE_ACK";
    case EventType.EVENT_TYPE_STATUS:
      return "EVENT_TYPE_STATUS";
    case EventType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ControlFrame is sent by WebSocket clients to control the bot daemon. */
export interface ControlFrame {
  type: ControlType;
  id: string;
  payload?:
    | { $case: "sendMessage"; sendMessage: SendMessagePayload }
    | { $case: "sendReaction"; sendReaction: SendReactionPayload }
    | { $case: "editMessage"; editMessage: EditMessagePayload }
    | { $case: "revokeMessage"; revokeMessage: RevokeMessagePayload }
    | { $case: "getStatus"; getStatus: GetStatusPayload }
    | { $case: "disconnect"; disconnect: DisconnectPayload }
    | { $case: "logout"; logout: LogoutPayload }
    | { $case: "requestPairCode"; requestPairCode: RequestPairCodePayload }
    | { $case: "requestPairQr"; requestPairQr: RequestPairQRPayload }
    | undefined;
}

export interface RequestPairCodePayload {
  phoneNumber: string;
}

export interface RequestPairQRPayload {
}

/** EventFrame is sent by the bot daemon to connected WebSocket clients. */
export interface EventFrame {
  type: EventType;
  id: string;
  payload?:
    | { $case: "ack"; ack: AckPayload }
    | { $case: "status"; status: StatusPayload }
    | { $case: "pairQr"; pairQr: PairQRPayload }
    | { $case: "pairCode"; pairCode: PairCodePayload }
    | { $case: "pairError"; pairError: PairErrorPayload }
    | { $case: "message"; message: IncomingMessagePayload }
    | { $case: "incomingCall"; incomingCall: IncomingCallPayload }
    | undefined;
}

export interface SendMessagePayload {
  to: string;
  text: string;
  quoteId?: string | undefined;
  quoteSender?: string | undefined;
}

export interface SendReactionPayload {
  to: string;
  messageId: string;
  sender?: string | undefined;
  emoji: string;
}

export interface EditMessagePayload {
  to: string;
  messageId: string;
  newText: string;
}

export interface RevokeMessagePayload {
  to: string;
  messageId: string;
  originalSender?: string | undefined;
}

export interface GetStatusPayload {
}

export interface DisconnectPayload {
}

export interface LogoutPayload {
}

export interface AckPayload {
  ok: boolean;
  error?: string | undefined;
}

export interface StatusPayload {
  connected: boolean;
  loggedIn: boolean;
  jid?: string | undefined;
  pushName?: string | undefined;
}

export interface PairQRPayload {
  code: string;
}

export interface PairCodePayload {
  code: string;
}

export interface PairErrorPayload {
  reason: string;
}

export interface IncomingMessagePayload {
  from: string;
  chat: string;
  sender: string;
  text: string;
  messageId: string;
  pushName?: string | undefined;
  timestampUnix: number;
  isGroup: boolean;
  isFromMe: boolean;
  mediaType?: string | undefined;
  quotedId?: string | undefined;
  quotedText?: string | undefined;
}

export interface IncomingCallPayload {
  callId: string;
  from: string;
  timestampUnix: number;
}

function createBaseControlFrame(): ControlFrame {
  return { type: 0, id: "", payload: undefined };
}

export const ControlFrame: MessageFns<ControlFrame> = {
  encode(message: ControlFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    switch (message.payload?.$case) {
      case "sendMessage":
        SendMessagePayload.encode(message.payload.sendMessage, writer.uint32(26).fork()).join();
        break;
      case "sendReaction":
        SendReactionPayload.encode(message.payload.sendReaction, writer.uint32(34).fork()).join();
        break;
      case "editMessage":
        EditMessagePayload.encode(message.payload.editMessage, writer.uint32(42).fork()).join();
        break;
      case "revokeMessage":
        RevokeMessagePayload.encode(message.payload.revokeMessage, writer.uint32(50).fork()).join();
        break;
      case "getStatus":
        GetStatusPayload.encode(message.payload.getStatus, writer.uint32(58).fork()).join();
        break;
      case "disconnect":
        DisconnectPayload.encode(message.payload.disconnect, writer.uint32(66).fork()).join();
        break;
      case "logout":
        LogoutPayload.encode(message.payload.logout, writer.uint32(74).fork()).join();
        break;
      case "requestPairCode":
        RequestPairCodePayload.encode(message.payload.requestPairCode, writer.uint32(82).fork()).join();
        break;
      case "requestPairQr":
        RequestPairQRPayload.encode(message.payload.requestPairQr, writer.uint32(90).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ControlFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseControlFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = { $case: "sendMessage", sendMessage: SendMessagePayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = {
            $case: "sendReaction",
            sendReaction: SendReactionPayload.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.payload = { $case: "editMessage", editMessage: EditMessagePayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payload = {
            $case: "revokeMessage",
            revokeMessage: RevokeMessagePayload.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.payload = { $case: "getStatus", getStatus: GetStatusPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.payload = { $case: "disconnect", disconnect: DisconnectPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.payload = { $case: "logout", logout: LogoutPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payload = {
            $case: "requestPairCode",
            requestPairCode: RequestPairCodePayload.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.payload = {
            $case: "requestPairQr",
            requestPairQr: RequestPairQRPayload.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ControlFrame {
    return {
      type: isSet(object.type) ? controlTypeFromJSON(object.type) : 0,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      payload: isSet(object.sendMessage)
        ? { $case: "sendMessage", sendMessage: SendMessagePayload.fromJSON(object.sendMessage) }
        : isSet(object.send_message)
        ? { $case: "sendMessage", sendMessage: SendMessagePayload.fromJSON(object.send_message) }
        : isSet(object.sendReaction)
        ? { $case: "sendReaction", sendReaction: SendReactionPayload.fromJSON(object.sendReaction) }
        : isSet(object.send_reaction)
        ? { $case: "sendReaction", sendReaction: SendReactionPayload.fromJSON(object.send_reaction) }
        : isSet(object.editMessage)
        ? { $case: "editMessage", editMessage: EditMessagePayload.fromJSON(object.editMessage) }
        : isSet(object.edit_message)
        ? { $case: "editMessage", editMessage: EditMessagePayload.fromJSON(object.edit_message) }
        : isSet(object.revokeMessage)
        ? { $case: "revokeMessage", revokeMessage: RevokeMessagePayload.fromJSON(object.revokeMessage) }
        : isSet(object.revoke_message)
        ? { $case: "revokeMessage", revokeMessage: RevokeMessagePayload.fromJSON(object.revoke_message) }
        : isSet(object.getStatus)
        ? { $case: "getStatus", getStatus: GetStatusPayload.fromJSON(object.getStatus) }
        : isSet(object.get_status)
        ? { $case: "getStatus", getStatus: GetStatusPayload.fromJSON(object.get_status) }
        : isSet(object.disconnect)
        ? { $case: "disconnect", disconnect: DisconnectPayload.fromJSON(object.disconnect) }
        : isSet(object.logout)
        ? { $case: "logout", logout: LogoutPayload.fromJSON(object.logout) }
        : isSet(object.requestPairCode)
        ? { $case: "requestPairCode", requestPairCode: RequestPairCodePayload.fromJSON(object.requestPairCode) }
        : isSet(object.request_pair_code)
        ? { $case: "requestPairCode", requestPairCode: RequestPairCodePayload.fromJSON(object.request_pair_code) }
        : isSet(object.requestPairQr)
        ? { $case: "requestPairQr", requestPairQr: RequestPairQRPayload.fromJSON(object.requestPairQr) }
        : isSet(object.request_pair_qr)
        ? { $case: "requestPairQr", requestPairQr: RequestPairQRPayload.fromJSON(object.request_pair_qr) }
        : undefined,
    };
  },

  toJSON(message: ControlFrame): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = controlTypeToJSON(message.type);
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.payload?.$case === "sendMessage") {
      obj.sendMessage = SendMessagePayload.toJSON(message.payload.sendMessage);
    } else if (message.payload?.$case === "sendReaction") {
      obj.sendReaction = SendReactionPayload.toJSON(message.payload.sendReaction);
    } else if (message.payload?.$case === "editMessage") {
      obj.editMessage = EditMessagePayload.toJSON(message.payload.editMessage);
    } else if (message.payload?.$case === "revokeMessage") {
      obj.revokeMessage = RevokeMessagePayload.toJSON(message.payload.revokeMessage);
    } else if (message.payload?.$case === "getStatus") {
      obj.getStatus = GetStatusPayload.toJSON(message.payload.getStatus);
    } else if (message.payload?.$case === "disconnect") {
      obj.disconnect = DisconnectPayload.toJSON(message.payload.disconnect);
    } else if (message.payload?.$case === "logout") {
      obj.logout = LogoutPayload.toJSON(message.payload.logout);
    } else if (message.payload?.$case === "requestPairCode") {
      obj.requestPairCode = RequestPairCodePayload.toJSON(message.payload.requestPairCode);
    } else if (message.payload?.$case === "requestPairQr") {
      obj.requestPairQr = RequestPairQRPayload.toJSON(message.payload.requestPairQr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ControlFrame>, I>>(base?: I): ControlFrame {
    return ControlFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ControlFrame>, I>>(object: I): ControlFrame {
    const message = createBaseControlFrame();
    message.type = object.type ?? 0;
    message.id = object.id ?? "";
    switch (object.payload?.$case) {
      case "sendMessage": {
        if (object.payload?.sendMessage !== undefined && object.payload?.sendMessage !== null) {
          message.payload = {
            $case: "sendMessage",
            sendMessage: SendMessagePayload.fromPartial(object.payload.sendMessage),
          };
        }
        break;
      }
      case "sendReaction": {
        if (object.payload?.sendReaction !== undefined && object.payload?.sendReaction !== null) {
          message.payload = {
            $case: "sendReaction",
            sendReaction: SendReactionPayload.fromPartial(object.payload.sendReaction),
          };
        }
        break;
      }
      case "editMessage": {
        if (object.payload?.editMessage !== undefined && object.payload?.editMessage !== null) {
          message.payload = {
            $case: "editMessage",
            editMessage: EditMessagePayload.fromPartial(object.payload.editMessage),
          };
        }
        break;
      }
      case "revokeMessage": {
        if (object.payload?.revokeMessage !== undefined && object.payload?.revokeMessage !== null) {
          message.payload = {
            $case: "revokeMessage",
            revokeMessage: RevokeMessagePayload.fromPartial(object.payload.revokeMessage),
          };
        }
        break;
      }
      case "getStatus": {
        if (object.payload?.getStatus !== undefined && object.payload?.getStatus !== null) {
          message.payload = { $case: "getStatus", getStatus: GetStatusPayload.fromPartial(object.payload.getStatus) };
        }
        break;
      }
      case "disconnect": {
        if (object.payload?.disconnect !== undefined && object.payload?.disconnect !== null) {
          message.payload = {
            $case: "disconnect",
            disconnect: DisconnectPayload.fromPartial(object.payload.disconnect),
          };
        }
        break;
      }
      case "logout": {
        if (object.payload?.logout !== undefined && object.payload?.logout !== null) {
          message.payload = { $case: "logout", logout: LogoutPayload.fromPartial(object.payload.logout) };
        }
        break;
      }
      case "requestPairCode": {
        if (object.payload?.requestPairCode !== undefined && object.payload?.requestPairCode !== null) {
          message.payload = {
            $case: "requestPairCode",
            requestPairCode: RequestPairCodePayload.fromPartial(object.payload.requestPairCode),
          };
        }
        break;
      }
      case "requestPairQr": {
        if (object.payload?.requestPairQr !== undefined && object.payload?.requestPairQr !== null) {
          message.payload = {
            $case: "requestPairQr",
            requestPairQr: RequestPairQRPayload.fromPartial(object.payload.requestPairQr),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseRequestPairCodePayload(): RequestPairCodePayload {
  return { phoneNumber: "" };
}

export const RequestPairCodePayload: MessageFns<RequestPairCodePayload> = {
  encode(message: RequestPairCodePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phoneNumber !== "") {
      writer.uint32(10).string(message.phoneNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestPairCodePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestPairCodePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestPairCodePayload {
    return {
      phoneNumber: isSet(object.phoneNumber)
        ? globalThis.String(object.phoneNumber)
        : isSet(object.phone_number)
        ? globalThis.String(object.phone_number)
        : "",
    };
  },

  toJSON(message: RequestPairCodePayload): unknown {
    const obj: any = {};
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestPairCodePayload>, I>>(base?: I): RequestPairCodePayload {
    return RequestPairCodePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestPairCodePayload>, I>>(object: I): RequestPairCodePayload {
    const message = createBaseRequestPairCodePayload();
    message.phoneNumber = object.phoneNumber ?? "";
    return message;
  },
};

function createBaseRequestPairQRPayload(): RequestPairQRPayload {
  return {};
}

export const RequestPairQRPayload: MessageFns<RequestPairQRPayload> = {
  encode(_: RequestPairQRPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestPairQRPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestPairQRPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RequestPairQRPayload {
    return {};
  },

  toJSON(_: RequestPairQRPayload): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestPairQRPayload>, I>>(base?: I): RequestPairQRPayload {
    return RequestPairQRPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestPairQRPayload>, I>>(_: I): RequestPairQRPayload {
    const message = createBaseRequestPairQRPayload();
    return message;
  },
};

function createBaseEventFrame(): EventFrame {
  return { type: 0, id: "", payload: undefined };
}

export const EventFrame: MessageFns<EventFrame> = {
  encode(message: EventFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    switch (message.payload?.$case) {
      case "ack":
        AckPayload.encode(message.payload.ack, writer.uint32(26).fork()).join();
        break;
      case "status":
        StatusPayload.encode(message.payload.status, writer.uint32(34).fork()).join();
        break;
      case "pairQr":
        PairQRPayload.encode(message.payload.pairQr, writer.uint32(42).fork()).join();
        break;
      case "pairCode":
        PairCodePayload.encode(message.payload.pairCode, writer.uint32(50).fork()).join();
        break;
      case "pairError":
        PairErrorPayload.encode(message.payload.pairError, writer.uint32(58).fork()).join();
        break;
      case "message":
        IncomingMessagePayload.encode(message.payload.message, writer.uint32(66).fork()).join();
        break;
      case "incomingCall":
        IncomingCallPayload.encode(message.payload.incomingCall, writer.uint32(74).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = { $case: "ack", ack: AckPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = { $case: "status", status: StatusPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.payload = { $case: "pairQr", pairQr: PairQRPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payload = { $case: "pairCode", pairCode: PairCodePayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.payload = { $case: "pairError", pairError: PairErrorPayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.payload = { $case: "message", message: IncomingMessagePayload.decode(reader, reader.uint32()) };
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.payload = {
            $case: "incomingCall",
            incomingCall: IncomingCallPayload.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventFrame {
    return {
      type: isSet(object.type) ? eventTypeFromJSON(object.type) : 0,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      payload: isSet(object.ack)
        ? { $case: "ack", ack: AckPayload.fromJSON(object.ack) }
        : isSet(object.status)
        ? { $case: "status", status: StatusPayload.fromJSON(object.status) }
        : isSet(object.pairQr)
        ? { $case: "pairQr", pairQr: PairQRPayload.fromJSON(object.pairQr) }
        : isSet(object.pair_qr)
        ? { $case: "pairQr", pairQr: PairQRPayload.fromJSON(object.pair_qr) }
        : isSet(object.pairCode)
        ? { $case: "pairCode", pairCode: PairCodePayload.fromJSON(object.pairCode) }
        : isSet(object.pair_code)
        ? { $case: "pairCode", pairCode: PairCodePayload.fromJSON(object.pair_code) }
        : isSet(object.pairError)
        ? { $case: "pairError", pairError: PairErrorPayload.fromJSON(object.pairError) }
        : isSet(object.pair_error)
        ? { $case: "pairError", pairError: PairErrorPayload.fromJSON(object.pair_error) }
        : isSet(object.message)
        ? { $case: "message", message: IncomingMessagePayload.fromJSON(object.message) }
        : isSet(object.incomingCall)
        ? { $case: "incomingCall", incomingCall: IncomingCallPayload.fromJSON(object.incomingCall) }
        : isSet(object.incoming_call)
        ? { $case: "incomingCall", incomingCall: IncomingCallPayload.fromJSON(object.incoming_call) }
        : undefined,
    };
  },

  toJSON(message: EventFrame): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = eventTypeToJSON(message.type);
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.payload?.$case === "ack") {
      obj.ack = AckPayload.toJSON(message.payload.ack);
    } else if (message.payload?.$case === "status") {
      obj.status = StatusPayload.toJSON(message.payload.status);
    } else if (message.payload?.$case === "pairQr") {
      obj.pairQr = PairQRPayload.toJSON(message.payload.pairQr);
    } else if (message.payload?.$case === "pairCode") {
      obj.pairCode = PairCodePayload.toJSON(message.payload.pairCode);
    } else if (message.payload?.$case === "pairError") {
      obj.pairError = PairErrorPayload.toJSON(message.payload.pairError);
    } else if (message.payload?.$case === "message") {
      obj.message = IncomingMessagePayload.toJSON(message.payload.message);
    } else if (message.payload?.$case === "incomingCall") {
      obj.incomingCall = IncomingCallPayload.toJSON(message.payload.incomingCall);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventFrame>, I>>(base?: I): EventFrame {
    return EventFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventFrame>, I>>(object: I): EventFrame {
    const message = createBaseEventFrame();
    message.type = object.type ?? 0;
    message.id = object.id ?? "";
    switch (object.payload?.$case) {
      case "ack": {
        if (object.payload?.ack !== undefined && object.payload?.ack !== null) {
          message.payload = { $case: "ack", ack: AckPayload.fromPartial(object.payload.ack) };
        }
        break;
      }
      case "status": {
        if (object.payload?.status !== undefined && object.payload?.status !== null) {
          message.payload = { $case: "status", status: StatusPayload.fromPartial(object.payload.status) };
        }
        break;
      }
      case "pairQr": {
        if (object.payload?.pairQr !== undefined && object.payload?.pairQr !== null) {
          message.payload = { $case: "pairQr", pairQr: PairQRPayload.fromPartial(object.payload.pairQr) };
        }
        break;
      }
      case "pairCode": {
        if (object.payload?.pairCode !== undefined && object.payload?.pairCode !== null) {
          message.payload = { $case: "pairCode", pairCode: PairCodePayload.fromPartial(object.payload.pairCode) };
        }
        break;
      }
      case "pairError": {
        if (object.payload?.pairError !== undefined && object.payload?.pairError !== null) {
          message.payload = { $case: "pairError", pairError: PairErrorPayload.fromPartial(object.payload.pairError) };
        }
        break;
      }
      case "message": {
        if (object.payload?.message !== undefined && object.payload?.message !== null) {
          message.payload = { $case: "message", message: IncomingMessagePayload.fromPartial(object.payload.message) };
        }
        break;
      }
      case "incomingCall": {
        if (object.payload?.incomingCall !== undefined && object.payload?.incomingCall !== null) {
          message.payload = {
            $case: "incomingCall",
            incomingCall: IncomingCallPayload.fromPartial(object.payload.incomingCall),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseSendMessagePayload(): SendMessagePayload {
  return { to: "", text: "", quoteId: undefined, quoteSender: undefined };
}

export const SendMessagePayload: MessageFns<SendMessagePayload> = {
  encode(message: SendMessagePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to !== "") {
      writer.uint32(10).string(message.to);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.quoteId !== undefined) {
      writer.uint32(26).string(message.quoteId);
    }
    if (message.quoteSender !== undefined) {
      writer.uint32(34).string(message.quoteSender);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessagePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessagePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.quoteId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.quoteSender = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessagePayload {
    return {
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      quoteId: isSet(object.quoteId)
        ? globalThis.String(object.quoteId)
        : isSet(object.quote_id)
        ? globalThis.String(object.quote_id)
        : undefined,
      quoteSender: isSet(object.quoteSender)
        ? globalThis.String(object.quoteSender)
        : isSet(object.quote_sender)
        ? globalThis.String(object.quote_sender)
        : undefined,
    };
  },

  toJSON(message: SendMessagePayload): unknown {
    const obj: any = {};
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.quoteId !== undefined) {
      obj.quoteId = message.quoteId;
    }
    if (message.quoteSender !== undefined) {
      obj.quoteSender = message.quoteSender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessagePayload>, I>>(base?: I): SendMessagePayload {
    return SendMessagePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessagePayload>, I>>(object: I): SendMessagePayload {
    const message = createBaseSendMessagePayload();
    message.to = object.to ?? "";
    message.text = object.text ?? "";
    message.quoteId = object.quoteId ?? undefined;
    message.quoteSender = object.quoteSender ?? undefined;
    return message;
  },
};

function createBaseSendReactionPayload(): SendReactionPayload {
  return { to: "", messageId: "", sender: undefined, emoji: "" };
}

export const SendReactionPayload: MessageFns<SendReactionPayload> = {
  encode(message: SendReactionPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to !== "") {
      writer.uint32(10).string(message.to);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.sender !== undefined) {
      writer.uint32(26).string(message.sender);
    }
    if (message.emoji !== "") {
      writer.uint32(34).string(message.emoji);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendReactionPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendReactionPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.emoji = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendReactionPayload {
    return {
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      sender: isSet(object.sender) ? globalThis.String(object.sender) : undefined,
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
    };
  },

  toJSON(message: SendReactionPayload): unknown {
    const obj: any = {};
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.sender !== undefined) {
      obj.sender = message.sender;
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendReactionPayload>, I>>(base?: I): SendReactionPayload {
    return SendReactionPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendReactionPayload>, I>>(object: I): SendReactionPayload {
    const message = createBaseSendReactionPayload();
    message.to = object.to ?? "";
    message.messageId = object.messageId ?? "";
    message.sender = object.sender ?? undefined;
    message.emoji = object.emoji ?? "";
    return message;
  },
};

function createBaseEditMessagePayload(): EditMessagePayload {
  return { to: "", messageId: "", newText: "" };
}

export const EditMessagePayload: MessageFns<EditMessagePayload> = {
  encode(message: EditMessagePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to !== "") {
      writer.uint32(10).string(message.to);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.newText !== "") {
      writer.uint32(26).string(message.newText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditMessagePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditMessagePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditMessagePayload {
    return {
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      newText: isSet(object.newText)
        ? globalThis.String(object.newText)
        : isSet(object.new_text)
        ? globalThis.String(object.new_text)
        : "",
    };
  },

  toJSON(message: EditMessagePayload): unknown {
    const obj: any = {};
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.newText !== "") {
      obj.newText = message.newText;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EditMessagePayload>, I>>(base?: I): EditMessagePayload {
    return EditMessagePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EditMessagePayload>, I>>(object: I): EditMessagePayload {
    const message = createBaseEditMessagePayload();
    message.to = object.to ?? "";
    message.messageId = object.messageId ?? "";
    message.newText = object.newText ?? "";
    return message;
  },
};

function createBaseRevokeMessagePayload(): RevokeMessagePayload {
  return { to: "", messageId: "", originalSender: undefined };
}

export const RevokeMessagePayload: MessageFns<RevokeMessagePayload> = {
  encode(message: RevokeMessagePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to !== "") {
      writer.uint32(10).string(message.to);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.originalSender !== undefined) {
      writer.uint32(26).string(message.originalSender);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeMessagePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRevokeMessagePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.originalSender = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RevokeMessagePayload {
    return {
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      originalSender: isSet(object.originalSender)
        ? globalThis.String(object.originalSender)
        : isSet(object.original_sender)
        ? globalThis.String(object.original_sender)
        : undefined,
    };
  },

  toJSON(message: RevokeMessagePayload): unknown {
    const obj: any = {};
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.originalSender !== undefined) {
      obj.originalSender = message.originalSender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RevokeMessagePayload>, I>>(base?: I): RevokeMessagePayload {
    return RevokeMessagePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeMessagePayload>, I>>(object: I): RevokeMessagePayload {
    const message = createBaseRevokeMessagePayload();
    message.to = object.to ?? "";
    message.messageId = object.messageId ?? "";
    message.originalSender = object.originalSender ?? undefined;
    return message;
  },
};

function createBaseGetStatusPayload(): GetStatusPayload {
  return {};
}

export const GetStatusPayload: MessageFns<GetStatusPayload> = {
  encode(_: GetStatusPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatusPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatusPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetStatusPayload {
    return {};
  },

  toJSON(_: GetStatusPayload): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatusPayload>, I>>(base?: I): GetStatusPayload {
    return GetStatusPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatusPayload>, I>>(_: I): GetStatusPayload {
    const message = createBaseGetStatusPayload();
    return message;
  },
};

function createBaseDisconnectPayload(): DisconnectPayload {
  return {};
}

export const DisconnectPayload: MessageFns<DisconnectPayload> = {
  encode(_: DisconnectPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisconnectPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisconnectPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DisconnectPayload {
    return {};
  },

  toJSON(_: DisconnectPayload): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DisconnectPayload>, I>>(base?: I): DisconnectPayload {
    return DisconnectPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisconnectPayload>, I>>(_: I): DisconnectPayload {
    const message = createBaseDisconnectPayload();
    return message;
  },
};

function createBaseLogoutPayload(): LogoutPayload {
  return {};
}

export const LogoutPayload: MessageFns<LogoutPayload> = {
  encode(_: LogoutPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LogoutPayload {
    return {};
  },

  toJSON(_: LogoutPayload): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutPayload>, I>>(base?: I): LogoutPayload {
    return LogoutPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutPayload>, I>>(_: I): LogoutPayload {
    const message = createBaseLogoutPayload();
    return message;
  },
};

function createBaseAckPayload(): AckPayload {
  return { ok: false, error: undefined };
}

export const AckPayload: MessageFns<AckPayload> = {
  encode(message: AckPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AckPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAckPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AckPayload {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
    };
  },

  toJSON(message: AckPayload): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AckPayload>, I>>(base?: I): AckPayload {
    return AckPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AckPayload>, I>>(object: I): AckPayload {
    const message = createBaseAckPayload();
    message.ok = object.ok ?? false;
    message.error = object.error ?? undefined;
    return message;
  },
};

function createBaseStatusPayload(): StatusPayload {
  return { connected: false, loggedIn: false, jid: undefined, pushName: undefined };
}

export const StatusPayload: MessageFns<StatusPayload> = {
  encode(message: StatusPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connected !== false) {
      writer.uint32(8).bool(message.connected);
    }
    if (message.loggedIn !== false) {
      writer.uint32(16).bool(message.loggedIn);
    }
    if (message.jid !== undefined) {
      writer.uint32(26).string(message.jid);
    }
    if (message.pushName !== undefined) {
      writer.uint32(34).string(message.pushName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.connected = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.loggedIn = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jid = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pushName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatusPayload {
    return {
      connected: isSet(object.connected) ? globalThis.Boolean(object.connected) : false,
      loggedIn: isSet(object.loggedIn)
        ? globalThis.Boolean(object.loggedIn)
        : isSet(object.logged_in)
        ? globalThis.Boolean(object.logged_in)
        : false,
      jid: isSet(object.jid) ? globalThis.String(object.jid) : undefined,
      pushName: isSet(object.pushName)
        ? globalThis.String(object.pushName)
        : isSet(object.push_name)
        ? globalThis.String(object.push_name)
        : undefined,
    };
  },

  toJSON(message: StatusPayload): unknown {
    const obj: any = {};
    if (message.connected !== false) {
      obj.connected = message.connected;
    }
    if (message.loggedIn !== false) {
      obj.loggedIn = message.loggedIn;
    }
    if (message.jid !== undefined) {
      obj.jid = message.jid;
    }
    if (message.pushName !== undefined) {
      obj.pushName = message.pushName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusPayload>, I>>(base?: I): StatusPayload {
    return StatusPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusPayload>, I>>(object: I): StatusPayload {
    const message = createBaseStatusPayload();
    message.connected = object.connected ?? false;
    message.loggedIn = object.loggedIn ?? false;
    message.jid = object.jid ?? undefined;
    message.pushName = object.pushName ?? undefined;
    return message;
  },
};

function createBasePairQRPayload(): PairQRPayload {
  return { code: "" };
}

export const PairQRPayload: MessageFns<PairQRPayload> = {
  encode(message: PairQRPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PairQRPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePairQRPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PairQRPayload {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: PairQRPayload): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PairQRPayload>, I>>(base?: I): PairQRPayload {
    return PairQRPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PairQRPayload>, I>>(object: I): PairQRPayload {
    const message = createBasePairQRPayload();
    message.code = object.code ?? "";
    return message;
  },
};

function createBasePairCodePayload(): PairCodePayload {
  return { code: "" };
}

export const PairCodePayload: MessageFns<PairCodePayload> = {
  encode(message: PairCodePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PairCodePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePairCodePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PairCodePayload {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: PairCodePayload): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PairCodePayload>, I>>(base?: I): PairCodePayload {
    return PairCodePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PairCodePayload>, I>>(object: I): PairCodePayload {
    const message = createBasePairCodePayload();
    message.code = object.code ?? "";
    return message;
  },
};

function createBasePairErrorPayload(): PairErrorPayload {
  return { reason: "" };
}

export const PairErrorPayload: MessageFns<PairErrorPayload> = {
  encode(message: PairErrorPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reason !== "") {
      writer.uint32(10).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PairErrorPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePairErrorPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PairErrorPayload {
    return { reason: isSet(object.reason) ? globalThis.String(object.reason) : "" };
  },

  toJSON(message: PairErrorPayload): unknown {
    const obj: any = {};
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PairErrorPayload>, I>>(base?: I): PairErrorPayload {
    return PairErrorPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PairErrorPayload>, I>>(object: I): PairErrorPayload {
    const message = createBasePairErrorPayload();
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseIncomingMessagePayload(): IncomingMessagePayload {
  return {
    from: "",
    chat: "",
    sender: "",
    text: "",
    messageId: "",
    pushName: undefined,
    timestampUnix: 0,
    isGroup: false,
    isFromMe: false,
    mediaType: undefined,
    quotedId: undefined,
    quotedText: undefined,
  };
}

export const IncomingMessagePayload: MessageFns<IncomingMessagePayload> = {
  encode(message: IncomingMessagePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.chat !== "") {
      writer.uint32(18).string(message.chat);
    }
    if (message.sender !== "") {
      writer.uint32(26).string(message.sender);
    }
    if (message.text !== "") {
      writer.uint32(34).string(message.text);
    }
    if (message.messageId !== "") {
      writer.uint32(42).string(message.messageId);
    }
    if (message.pushName !== undefined) {
      writer.uint32(50).string(message.pushName);
    }
    if (message.timestampUnix !== 0) {
      writer.uint32(56).int64(message.timestampUnix);
    }
    if (message.isGroup !== false) {
      writer.uint32(64).bool(message.isGroup);
    }
    if (message.isFromMe !== false) {
      writer.uint32(72).bool(message.isFromMe);
    }
    if (message.mediaType !== undefined) {
      writer.uint32(82).string(message.mediaType);
    }
    if (message.quotedId !== undefined) {
      writer.uint32(90).string(message.quotedId);
    }
    if (message.quotedText !== undefined) {
      writer.uint32(98).string(message.quotedText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncomingMessagePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncomingMessagePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chat = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.pushName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestampUnix = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isGroup = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isFromMe = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.mediaType = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.quotedId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.quotedText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IncomingMessagePayload {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      chat: isSet(object.chat) ? globalThis.String(object.chat) : "",
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      pushName: isSet(object.pushName)
        ? globalThis.String(object.pushName)
        : isSet(object.push_name)
        ? globalThis.String(object.push_name)
        : undefined,
      timestampUnix: isSet(object.timestampUnix)
        ? globalThis.Number(object.timestampUnix)
        : isSet(object.timestamp_unix)
        ? globalThis.Number(object.timestamp_unix)
        : 0,
      isGroup: isSet(object.isGroup)
        ? globalThis.Boolean(object.isGroup)
        : isSet(object.is_group)
        ? globalThis.Boolean(object.is_group)
        : false,
      isFromMe: isSet(object.isFromMe)
        ? globalThis.Boolean(object.isFromMe)
        : isSet(object.is_from_me)
        ? globalThis.Boolean(object.is_from_me)
        : false,
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : undefined,
      quotedId: isSet(object.quotedId)
        ? globalThis.String(object.quotedId)
        : isSet(object.quoted_id)
        ? globalThis.String(object.quoted_id)
        : undefined,
      quotedText: isSet(object.quotedText)
        ? globalThis.String(object.quotedText)
        : isSet(object.quoted_text)
        ? globalThis.String(object.quoted_text)
        : undefined,
    };
  },

  toJSON(message: IncomingMessagePayload): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.chat !== "") {
      obj.chat = message.chat;
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.pushName !== undefined) {
      obj.pushName = message.pushName;
    }
    if (message.timestampUnix !== 0) {
      obj.timestampUnix = Math.round(message.timestampUnix);
    }
    if (message.isGroup !== false) {
      obj.isGroup = message.isGroup;
    }
    if (message.isFromMe !== false) {
      obj.isFromMe = message.isFromMe;
    }
    if (message.mediaType !== undefined) {
      obj.mediaType = message.mediaType;
    }
    if (message.quotedId !== undefined) {
      obj.quotedId = message.quotedId;
    }
    if (message.quotedText !== undefined) {
      obj.quotedText = message.quotedText;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IncomingMessagePayload>, I>>(base?: I): IncomingMessagePayload {
    return IncomingMessagePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IncomingMessagePayload>, I>>(object: I): IncomingMessagePayload {
    const message = createBaseIncomingMessagePayload();
    message.from = object.from ?? "";
    message.chat = object.chat ?? "";
    message.sender = object.sender ?? "";
    message.text = object.text ?? "";
    message.messageId = object.messageId ?? "";
    message.pushName = object.pushName ?? undefined;
    message.timestampUnix = object.timestampUnix ?? 0;
    message.isGroup = object.isGroup ?? false;
    message.isFromMe = object.isFromMe ?? false;
    message.mediaType = object.mediaType ?? undefined;
    message.quotedId = object.quotedId ?? undefined;
    message.quotedText = object.quotedText ?? undefined;
    return message;
  },
};

function createBaseIncomingCallPayload(): IncomingCallPayload {
  return { callId: "", from: "", timestampUnix: 0 };
}

export const IncomingCallPayload: MessageFns<IncomingCallPayload> = {
  encode(message: IncomingCallPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.from !== "") {
      writer.uint32(18).string(message.from);
    }
    if (message.timestampUnix !== 0) {
      writer.uint32(24).int64(message.timestampUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncomingCallPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncomingCallPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestampUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IncomingCallPayload {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      timestampUnix: isSet(object.timestampUnix)
        ? globalThis.Number(object.timestampUnix)
        : isSet(object.timestamp_unix)
        ? globalThis.Number(object.timestamp_unix)
        : 0,
    };
  },

  toJSON(message: IncomingCallPayload): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.timestampUnix !== 0) {
      obj.timestampUnix = Math.round(message.timestampUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IncomingCallPayload>, I>>(base?: I): IncomingCallPayload {
    return IncomingCallPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IncomingCallPayload>, I>>(object: I): IncomingCallPayload {
    const message = createBaseIncomingCallPayload();
    message.callId = object.callId ?? "";
    message.from = object.from ?? "";
    message.timestampUnix = object.timestampUnix ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
