services:
  - type: web
    name: whatsrook
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        sync: false
      - key: PAIR
        value: "true"
      - key: CLIENT
        sync: false
        value: "ios"