services:
  - type: web
    name: whatsrook
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        sync: false
      - key: PAIR
        value: "true"
      - key: CLIENT
        value: "ios"
    disk:
      name: whatsrook-auth
      mountPath: /app/auth
      sizeGB: 1
