package commands

import (
	"testing"
)

func TestCookieCommandRegistration(t *testing.T) {
	cmdCookie, ok := Get("cookie")
	if !ok {
		t.Fatal("expected 'cookie' command to be registered")
	}
	if cmdCookie.Category != "media" {
		t.Errorf("expected category 'media', got %q", cmdCookie.Category)
	}

	cmdSetCookie, ok := Get("setcookie")
	if !ok {
		t.Fatal("expected 'setcookie' command to be registered")
	}
	if cmdSetCookie.Category != "media" {
		t.Errorf("expected category 'media', got %q", cmdSetCookie.Category)
	}
}

func TestIsValidNetscapeCookie(t *testing.T) {
	validCookie := `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Get cookies.txt LOCALLY
.youtube.com	TRUE	/	TRUE	1785158262	VISITOR_INFO1_LIVE	sample_val
.youtube.com	TRUE	/	FALSE	1785158262	LOGIN_INFO	sample_val`

	if !IsValidNetscapeCookie(validCookie) {
		t.Error("expected valid Netscape cookie to return true")
	}

	invalidCookie := "this is random text not a cookie"
	if IsValidNetscapeCookie(invalidCookie) {
		t.Error("expected invalid text to return false")
	}

	emptyCookie := ""
	if IsValidNetscapeCookie(emptyCookie) {
		t.Error("expected empty string to return false")
	}
}
